//! Go `ast.As<Kind>().<Field>` accessors and `ast.Is<Kind>` / `ast.Is<X>Kind`
//! helpers from pinned typescript-go `internal/ast/ast_generated.go`.
//!
//! Generated by a one-off script from `ast_generated.go` (Go struct fields and
//! `Is*` functions) and `src/astdata/ast_generated.rs` (the `NodeData`
//! variants that hold the data). Regenerate instead of editing by hand.
//!
//! The `is_*` kind tests are `#[inline]`: they are one kind compare, and a
//! caller in another codegen unit must not pay a call for them.
//!
//! Rules (see PORTING.md "AST"):
//! - One `Node` method per exported Go node field. It works for every node
//!   struct that has the field and panics on other kinds, like a Go `AsX()`
//!   type assertion.
//! - Go fields that share a name with a Go `*Node` method (`Name`, `Body`,
//!   `Type`, `Expression`, `Text`, `Arguments`, ...) are not generated here.
//!   The `node.rs` method wins.
//! - Binder fields (`Symbol`, `LocalSymbol`, `Locals`, `NextContainer`,
//!   `FlowNode`, `EndFlowNode`, `ReturnFlowNode`) come from the node records
//!   and `NodeBindExtra` through `node.rs`. `SourceFile` fields other than `EndOfFileToken` come
//!   from `source_file_info` / `file_bind_data`.
//! - Unexported Go fields (`name`, `modifiers`, `facts`, `text`) are only
//!   reachable through Go `*Node` methods, so they are not generated.

// Node data is read with `with_data!` (Go reads node fields without a
// context; we reach the parsed arena through the installed program).
use crate::ast::synthetic::{list_of, with_data};
use crate::astdata::NodeData;
use crate::prelude::*;

/// Go `nil` for an optional child.
fn opt_node(file: usize, id: Option<crate::astdata::NodeId>) -> Node {
    match id {
        Some(id) => Node::new(file, id),
        None => Node::NIL,
    }
}

/// Go panics with a failed type assertion when `AsX()` gets the wrong kind.
#[cold]
fn field_panic(n: Node, field: &str) -> ! {
    panic!(
        "ast field {field} does not exist on node kind {:?}",
        n.kind()
    )
}

// ──────────────────────────────────────────────────────────────────────
// Node fields
// ──────────────────────────────────────────────────────────────────────

impl Node {
    // Go: ast/ast_generated.go:159 FullSignature
    /// Go `node.AsX().FullSignature` for: FunctionDeclaration, CallSignatureDeclaration, ConstructSignatureDeclaration, ConstructorDeclaration, GetAccessorDeclaration, SetAccessorDeclaration, IndexSignatureDeclaration, MethodSignatureDeclaration, MethodDeclaration, ArrowFunction, FunctionExpression, FunctionTypeNode, ConstructorTypeNode, JSDocSignature.
    #[must_use]
    pub fn full_signature(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::FunctionDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::CallSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ConstructSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ConstructorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::GetAccessorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::SetAccessorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::IndexSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::MethodSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::MethodDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ArrowFunction(d) => opt_node(file, d.full_signature),
            NodeData::FunctionExpression(d) => opt_node(file, d.full_signature),
            NodeData::FunctionTypeNode(d) => opt_node(file, d.full_signature),
            NodeData::ConstructorTypeNode(d) => opt_node(file, d.full_signature),
            NodeData::JsDocSignature(d) => opt_node(file, d.full_signature),
            _ => field_panic(self, "FullSignature"),
        })
    }

    // Go: ast/ast_generated.go:164 AsteriskToken
    /// Go `node.AsX().AsteriskToken` for: FunctionDeclaration, ConstructorDeclaration, GetAccessorDeclaration, SetAccessorDeclaration, MethodDeclaration, YieldExpression, ArrowFunction, FunctionExpression, ModuleDeclaration.
    #[must_use]
    pub fn asterisk_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::FunctionDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::ConstructorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::GetAccessorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::SetAccessorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::MethodDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::YieldExpression(d) => opt_node(file, d.asterisk_token),
            NodeData::ArrowFunction(d) => opt_node(file, d.asterisk_token),
            NodeData::FunctionExpression(d) => opt_node(file, d.asterisk_token),
            NodeData::ModuleDeclaration(d) => opt_node(file, d.asterisk_token),
            _ => field_panic(self, "AsteriskToken"),
        })
    }

    // Go: ast/ast_generated.go:182 HeritageClauses
    /// Go `node.AsX().HeritageClauses` for: ClassDeclaration, ClassExpression, InterfaceDeclaration.
    #[must_use]
    pub fn heritage_clauses(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::ClassDeclaration(d) => Some(d.heritage_clauses.as_ref().map(AnyList::Nodes)),
            NodeData::ClassExpression(d) => Some(d.heritage_clauses.as_ref().map(AnyList::Nodes)),
            NodeData::InterfaceDeclaration(d) =>
                Some(d.heritage_clauses.as_ref().map(AnyList::Nodes)),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "HeritageClauses"))
    }

    // Go: ast/ast_generated.go:186 TokenFlags
    /// Go `node.AsX().TokenFlags` for: StringLiteral, NumericLiteral, BigIntLiteral, RegularExpressionLiteral, NoSubstitutionTemplateLiteral, TemplateHead, TemplateMiddle, TemplateTail, JsxText.
    #[must_use]
    pub fn token_flags(self) -> TokenFlags {
        with_data!(self, |d| match d {
            NodeData::StringLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::NumericLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::BigIntLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::RegularExpressionLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::NoSubstitutionTemplateLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateHead(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateMiddle(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateTail(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::JsxText(d) => TokenFlags(d.token_flags.0 as i32),
            _ => field_panic(self, "TokenFlags"),
        })
    }

    // Go: ast/ast_generated.go:197 TemplateFlags
    /// Go `node.AsX().TemplateFlags` for: NoSubstitutionTemplateLiteral, TemplateHead, TemplateMiddle, TemplateTail.
    #[must_use]
    pub fn template_flags(self) -> TokenFlags {
        with_data!(self, |d| match d {
            NodeData::NoSubstitutionTemplateLiteral(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateHead(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateMiddle(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateTail(d) => TokenFlags(d.template_flags.0 as i32),
            _ => field_panic(self, "TemplateFlags"),
        })
    }

    // Go: ast/ast_generated.go:2321 Types
    /// Go `node.AsX().Types` for: HeritageClause, UnionTypeNode, IntersectionTypeNode.
    #[must_use]
    pub fn types(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::HeritageClause(d) => Some(Some(AnyList::Nodes(&d.types))),
            NodeData::UnionTypeNode(d) => Some(Some(AnyList::Nodes(&d.types))),
            NodeData::IntersectionTypeNode(d) => Some(Some(AnyList::Nodes(&d.types))),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "Types"))
    }

    // Go: ast/ast_generated.go:7053 Comment
    /// Go `node.AsX().Comment` for: JSDoc, JSDocTypeTag, JSDocUnknownTag, JSDocTemplateTag, JSDocReturnTag, JSDocPublicTag, JSDocPrivateTag, JSDocProtectedTag, JSDocReadonlyTag, JSDocOverrideTag, JSDocDeprecatedTag, JSDocSeeTag, JSDocImplementsTag, JSDocAugmentsTag, JSDocSatisfiesTag, JSDocThrowsTag, JSDocThisTag, JSDocImportTag, JSDocCallbackTag, JSDocOverloadTag, JSDocTypedefTag, JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn comment(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::JsDoc(d) => Some(Some(AnyList::Nodes(&d.comment))),
            NodeData::JsDocTypeTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocUnknownTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocTemplateTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocReturnTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocPublicTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocPrivateTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocProtectedTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocReadonlyTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocOverrideTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocDeprecatedTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocSeeTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocImplementsTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocAugmentsTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocSatisfiesTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocThrowsTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocThisTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocImportTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocCallbackTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocOverloadTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocTypedefTag(d) => Some(d.comment.as_ref().map(AnyList::Nodes)),
            NodeData::JsDocParameterOrPropertyTag(d) =>
                Some(d.comment.as_ref().map(AnyList::Nodes)),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "Comment"))
    }

    // Go: ast/ast_generated.go:839 Left
    /// Go `node.AsX().Left` for: QualifiedName, BinaryExpression.
    #[must_use]
    pub fn left(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::QualifiedName(d) => Node::new(file, d.left),
            NodeData::BinaryExpression(d) => Node::new(file, d.left),
            _ => field_panic(self, "Left"),
        })
    }

    // Go: ast/ast_generated.go:840 Right
    /// Go `node.AsX().Right` for: QualifiedName, BinaryExpression.
    #[must_use]
    pub fn right(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::QualifiedName(d) => Node::new(file, d.right),
            NodeData::BinaryExpression(d) => Node::new(file, d.right),
            _ => field_panic(self, "Right"),
        })
    }

    // Go: ast/ast_generated.go:824 ThenStatement
    /// Go `node.AsX().ThenStatement` for: IfStatement.
    #[must_use]
    pub fn then_statement(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::IfStatement(d) => Node::new(file, d.then_statement),
            _ => field_panic(self, "ThenStatement"),
        })
    }

    // Go: ast/ast_generated.go:825 ElseStatement
    /// Go `node.AsX().ElseStatement` for: IfStatement.
    #[must_use]
    pub fn else_statement(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::IfStatement(d) => opt_node(file, d.else_statement),
            _ => field_panic(self, "ElseStatement"),
        })
    }

    // Go: ast/ast_generated.go:1129 Condition
    /// Go `node.AsX().Condition` for: ForStatement, ConditionalExpression.
    #[must_use]
    pub fn condition(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ForStatement(d) => opt_node(file, d.condition),
            NodeData::ConditionalExpression(d) => Node::new(file, d.condition),
            _ => field_panic(self, "Condition"),
        })
    }

    // Go: ast/ast_generated.go:965 Incrementor
    /// Go `node.AsX().Incrementor` for: ForStatement.
    #[must_use]
    pub fn incrementor(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ForStatement(d) => opt_node(file, d.incrementor),
            _ => field_panic(self, "Incrementor"),
        })
    }

    // Go: ast/ast_generated.go:1018 AwaitModifier
    /// Go `node.AsX().AwaitModifier` for: ForInOrOfStatement.
    #[must_use]
    pub fn await_modifier(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ForInOrOfStatement(d) => opt_node(file, d.await_modifier),
            _ => field_panic(self, "AwaitModifier"),
        })
    }

    // Go: ast/ast_generated.go:1232 CaseBlock
    /// Go `node.AsX().CaseBlock` for: SwitchStatement.
    #[must_use]
    pub fn case_block(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::SwitchStatement(d) => Node::new(file, d.case_block),
            _ => field_panic(self, "CaseBlock"),
        })
    }

    // Go: ast/ast_generated.go:1278 Clauses
    /// Go `node.AsX().Clauses` for: CaseBlock.
    #[must_use]
    pub fn clauses(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::CaseBlock(d) => Some(Some(AnyList::Nodes(&d.clauses))),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "Clauses"))
    }

    // Go: ast/ast_generated.go:1323 FallthroughFlowNode
    /// Go `node.AsX().FallthroughFlowNode` for: CaseOrDefaultClause.
    /// PORT: the binder sets this field. `core::NodeBindData` has no
    /// separate slot, and case/default clauses have no Go `FlowNodeData`, so
    /// `bindCaseBlock` (binder_p3.rs) stores it in the clause's `flow_node`
    /// slot. The astdata value is not a Go flow node id and is not read.
    #[must_use]
    pub fn fallthrough_flow_node(self) -> FlowNodeId {
        with_data!(self, |d| match d {
            NodeData::CaseOrDefaultClause(_) => self.flow_node(),
            _ => field_panic(self, "FallthroughFlowNode"),
        })
    }

    // Go: ast/ast_generated.go:1415 TryBlock
    /// Go `node.AsX().TryBlock` for: TryStatement.
    #[must_use]
    pub fn try_block(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TryStatement(d) => Node::new(file, d.try_block),
            _ => field_panic(self, "TryBlock"),
        })
    }

    // Go: ast/ast_generated.go:1416 CatchClause
    /// Go `node.AsX().CatchClause` for: TryStatement.
    #[must_use]
    pub fn catch_clause(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TryStatement(d) => opt_node(file, d.catch_clause),
            _ => field_panic(self, "CatchClause"),
        })
    }

    // Go: ast/ast_generated.go:1417 FinallyBlock
    /// Go `node.AsX().FinallyBlock` for: TryStatement.
    #[must_use]
    pub fn finally_block(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TryStatement(d) => opt_node(file, d.finally_block),
            _ => field_panic(self, "FinallyBlock"),
        })
    }

    // Go: ast/ast_generated.go:1465 VariableDeclaration
    /// Go `node.AsX().VariableDeclaration` for: CatchClause.
    #[must_use]
    pub fn variable_declaration(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::CatchClause(d) => opt_node(file, d.variable_declaration),
            _ => field_panic(self, "VariableDeclaration"),
        })
    }

    // Go: ast/ast_generated.go:1466 Block
    /// Go `node.AsX().Block` for: CatchClause.
    #[must_use]
    pub fn block(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::CatchClause(d) => Node::new(file, d.block),
            _ => field_panic(self, "Block"),
        })
    }

    // Go: ast/ast_generated.go:1781 MultiLine
    /// Go `node.AsX().MultiLine` for: Block, ArrayLiteralExpression, ObjectLiteralExpression, ImportAttributes.
    #[must_use]
    pub fn multi_line(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::Block(d) => d.multi_line,
            NodeData::ArrayLiteralExpression(d) => d.multi_line,
            NodeData::ObjectLiteralExpression(d) => d.multi_line,
            NodeData::ImportAttributes(d) => d.multi_line,
            _ => field_panic(self, "MultiLine"),
        })
    }

    // Go: ast/ast_generated.go:1661 DeclarationList
    /// Go `node.AsX().DeclarationList` for: VariableStatement.
    #[must_use]
    pub fn declaration_list(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::VariableStatement(d) => Node::new(file, d.declaration_list),
            _ => field_panic(self, "DeclarationList"),
        })
    }

    // Go: ast/ast_generated.go:1704 ExclamationToken
    /// Go `node.AsX().ExclamationToken` for: VariableDeclaration.
    #[must_use]
    pub fn exclamation_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::VariableDeclaration(d) => opt_node(file, d.exclamation_token),
            _ => field_panic(self, "ExclamationToken"),
        })
    }

    // Go: ast/ast_generated.go:1755 Declarations
    /// Go `node.AsX().Declarations` for: VariableDeclarationList.
    #[must_use]
    pub fn declarations(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::VariableDeclarationList(d) => Some(Some(AnyList::Nodes(&d.declarations))),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "Declarations"))
    }

    // Go: ast/ast_generated.go:2006 DotDotDotToken
    /// Go `node.AsX().DotDotDotToken` for: ParameterDeclaration, BindingElement, NamedTupleMember, JsxExpression.
    #[must_use]
    pub fn dot_dot_dot_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ParameterDeclaration(d) => opt_node(file, d.dot_dot_dot_token),
            NodeData::BindingElement(d) => opt_node(file, d.dot_dot_dot_token),
            // PORT: an array binding hole, Go `BindingElement` with nil fields.
            NodeData::OmittedExpression(_) if self.kind() == SyntaxKind::BindingElement => {
                Node::NIL
            }
            NodeData::NamedTupleMember(d) => opt_node(file, d.dot_dot_dot_token),
            NodeData::JsxExpression(d) => opt_node(file, d.dot_dot_dot_token),
            _ => field_panic(self, "DotDotDotToken"),
        })
    }

    // Go: ast/ast_generated.go:2320 Token
    /// Go `node.AsX().Token` for: HeritageClause, ImportAttributes.
    #[must_use]
    pub fn token(self) -> SyntaxKind {
        with_data!(self, |d| match d {
            NodeData::HeritageClause(d) => d.token,
            NodeData::ImportAttributes(d) => d.token,
            _ => field_panic(self, "Token"),
        })
    }

    // Go: ast/ast_generated.go:2736 IsExportEquals
    /// Go `node.AsX().IsExportEquals` for: ExportAssignment.
    #[must_use]
    pub fn is_export_equals(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::ExportAssignment(d) => d.is_export_equals,
            _ => field_panic(self, "IsExportEquals"),
        })
    }

    // Go: ast/ast_generated.go:3726 OperatorToken
    /// Go `node.AsX().OperatorToken` for: BinaryExpression.
    #[must_use]
    pub fn operator_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::BinaryExpression(d) => Node::new(file, d.operator_token),
            _ => field_panic(self, "OperatorToken"),
        })
    }

    // Go: ast/ast_generated.go:3936 Operator
    /// Go `node.AsX().Operator` for: PrefixUnaryExpression, PostfixUnaryExpression, TypeOperatorNode.
    #[must_use]
    pub fn operator(self) -> SyntaxKind {
        with_data!(self, |d| match d {
            NodeData::PrefixUnaryExpression(d) => d.operator,
            NodeData::PostfixUnaryExpression(d) => d.operator,
            NodeData::TypeOperatorNode(d) => d.operator,
            _ => field_panic(self, "Operator"),
        })
    }

    // Go: ast/ast_generated.go:3937 Operand
    /// Go `node.AsX().Operand` for: PrefixUnaryExpression, PostfixUnaryExpression.
    #[must_use]
    pub fn operand(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::PrefixUnaryExpression(d) => Node::new(file, d.operand),
            NodeData::PostfixUnaryExpression(d) => Node::new(file, d.operand),
            _ => field_panic(self, "Operand"),
        })
    }

    // Go: ast/ast_generated.go:3906 EqualsGreaterThanToken
    /// Go `node.AsX().EqualsGreaterThanToken` for: ArrowFunction.
    #[must_use]
    pub fn equals_greater_than_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ArrowFunction(d) => Node::new(file, d.equals_greater_than_token),
            _ => field_panic(self, "EqualsGreaterThanToken"),
        })
    }

    // Go: ast/ast_generated.go:4101 WhenTrue
    /// Go `node.AsX().WhenTrue` for: ConditionalExpression.
    #[must_use]
    pub fn when_true(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalExpression(d) => Node::new(file, d.when_true),
            _ => field_panic(self, "WhenTrue"),
        })
    }

    // Go: ast/ast_generated.go:4102 ColonToken
    /// Go `node.AsX().ColonToken` for: ConditionalExpression.
    #[must_use]
    pub fn colon_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalExpression(d) => Node::new(file, d.colon_token),
            _ => field_panic(self, "ColonToken"),
        })
    }

    // Go: ast/ast_generated.go:4103 WhenFalse
    /// Go `node.AsX().WhenFalse` for: ConditionalExpression.
    #[must_use]
    pub fn when_false(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalExpression(d) => Node::new(file, d.when_false),
            _ => field_panic(self, "WhenFalse"),
        })
    }

    // Go: ast/ast_generated.go:4211 ArgumentExpression
    /// Go `node.AsX().ArgumentExpression` for: ElementAccessExpression.
    #[must_use]
    pub fn argument_expression(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ElementAccessExpression(d) => Node::new(file, d.argument_expression),
            _ => field_panic(self, "ArgumentExpression"),
        })
    }

    // Go: ast/ast_generated.go:4355 KeywordToken
    /// Go `node.AsX().KeywordToken` for: MetaProperty.
    #[must_use]
    pub fn keyword_token(self) -> SyntaxKind {
        with_data!(self, |d| match d {
            NodeData::MetaProperty(d) => d.keyword_token,
            _ => field_panic(self, "KeywordToken"),
        })
    }

    // Go: ast/ast_generated.go:4641 Head
    /// Go `node.AsX().Head` for: TemplateExpression, TemplateLiteralTypeNode.
    #[must_use]
    pub fn head(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TemplateExpression(d) => Node::new(file, d.head),
            NodeData::TemplateLiteralTypeNode(d) => Node::new(file, d.head),
            _ => field_panic(self, "Head"),
        })
    }

    // Go: ast/ast_generated.go:4642 TemplateSpans
    /// Go `node.AsX().TemplateSpans` for: TemplateExpression, TemplateLiteralTypeNode.
    #[must_use]
    pub fn template_spans(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::TemplateExpression(d) => Some(Some(AnyList::Nodes(&d.template_spans))),
            NodeData::TemplateLiteralTypeNode(d) => Some(Some(AnyList::Nodes(&d.template_spans))),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "TemplateSpans"))
    }

    // Go: ast/ast_generated.go:4687 Literal
    /// Go `node.AsX().Literal` for: TemplateSpan, LiteralTypeNode, TemplateLiteralTypeSpan.
    #[must_use]
    pub fn literal(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TemplateSpan(d) => Node::new(file, d.literal),
            NodeData::LiteralTypeNode(d) => Node::new(file, d.literal),
            NodeData::TemplateLiteralTypeSpan(d) => Node::new(file, d.literal),
            _ => field_panic(self, "Literal"),
        })
    }

    // Go: ast/ast_generated.go:4569 Tag
    /// Go `node.AsX().Tag` for: TaggedTemplateExpression.
    #[must_use]
    pub fn tag(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TaggedTemplateExpression(d) => Node::new(file, d.tag),
            _ => field_panic(self, "Tag"),
        })
    }

    // Go: ast/ast_generated.go:4572 Template
    /// Go `node.AsX().Template` for: TaggedTemplateExpression.
    #[must_use]
    pub fn template(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TaggedTemplateExpression(d) => Node::new(file, d.template),
            _ => field_panic(self, "Template"),
        })
    }

    // Go: ast/ast_generated.go:4851 EqualsToken
    /// Go `node.AsX().EqualsToken` for: ShorthandPropertyAssignment.
    #[must_use]
    pub fn equals_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ShorthandPropertyAssignment(d) => opt_node(file, d.equals_token),
            _ => field_panic(self, "EqualsToken"),
        })
    }

    // Go: ast/ast_generated.go:4852 ObjectAssignmentInitializer
    /// Go `node.AsX().ObjectAssignmentInitializer` for: ShorthandPropertyAssignment.
    #[must_use]
    pub fn object_assignment_initializer(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ShorthandPropertyAssignment(d) => {
                opt_node(file, d.object_assignment_initializer)
            }
            _ => field_panic(self, "ObjectAssignmentInitializer"),
        })
    }

    // Go: ast/ast_generated.go:5208 CheckType
    /// Go `node.AsX().CheckType` for: ConditionalTypeNode.
    #[must_use]
    pub fn check_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.check_type),
            _ => field_panic(self, "CheckType"),
        })
    }

    // Go: ast/ast_generated.go:5209 ExtendsType
    /// Go `node.AsX().ExtendsType` for: ConditionalTypeNode.
    #[must_use]
    pub fn extends_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.extends_type),
            _ => field_panic(self, "ExtendsType"),
        })
    }

    // Go: ast/ast_generated.go:5210 TrueType
    /// Go `node.AsX().TrueType` for: ConditionalTypeNode.
    #[must_use]
    pub fn true_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.true_type),
            _ => field_panic(self, "TrueType"),
        })
    }

    // Go: ast/ast_generated.go:5211 FalseType
    /// Go `node.AsX().FalseType` for: ConditionalTypeNode.
    #[must_use]
    pub fn false_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.false_type),
            _ => field_panic(self, "FalseType"),
        })
    }

    // Go: ast/ast_generated.go:5469 TypeParameter
    /// Go `node.AsX().TypeParameter` for: InferTypeNode, MappedTypeNode.
    #[must_use]
    pub fn type_parameter(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::InferTypeNode(d) => Node::new(file, d.type_parameter),
            NodeData::MappedTypeNode(d) => Node::new(file, d.type_parameter),
            _ => field_panic(self, "TypeParameter"),
        })
    }

    // Go: ast/ast_generated.go:5333 ElementType
    /// Go `node.AsX().ElementType` for: ArrayTypeNode.
    #[must_use]
    pub fn element_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ArrayTypeNode(d) => Node::new(file, d.element_type),
            _ => field_panic(self, "ElementType"),
        })
    }

    // Go: ast/ast_generated.go:5371 ObjectType
    /// Go `node.AsX().ObjectType` for: IndexedAccessTypeNode.
    #[must_use]
    pub fn object_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::IndexedAccessTypeNode(d) => Node::new(file, d.object_type),
            _ => field_panic(self, "ObjectType"),
        })
    }

    // Go: ast/ast_generated.go:5372 IndexType
    /// Go `node.AsX().IndexType` for: IndexedAccessTypeNode.
    #[must_use]
    pub fn index_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::IndexedAccessTypeNode(d) => Node::new(file, d.index_type),
            _ => field_panic(self, "IndexType"),
        })
    }

    // Go: ast/ast_generated.go:5411 TypeName
    /// Go `node.AsX().TypeName` for: TypeReferenceNode.
    // PERF: C2 (a hand edit; keep it when this file is made again). A tier 0
    // store TypeReference reads the child from the store column
    // (`frozen_store_child`), as `Node::name` does. Other kinds take the
    // data path, which panics like Go.
    #[must_use]
    pub fn type_name(self) -> Node {
        if let Some(type_name) = frozen_store_child(self, StoreChild::TypeName) {
            debug_assert!(
                with_data!(self, |d| matches!(d, NodeData::TypeReferenceNode(d)
                    if Node::new(self.file_index(), d.type_name) == type_name)),
                "C2 type name column"
            );
            return type_name;
        }
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TypeReferenceNode(d) => Node::new(file, d.type_name),
            _ => field_panic(self, "TypeName"),
        })
    }

    // Go: ast/ast_generated.go:5550 AssertsModifier
    /// Go `node.AsX().AssertsModifier` for: TypePredicateNode.
    #[must_use]
    pub fn asserts_modifier(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TypePredicateNode(d) => opt_node(file, d.asserts_modifier),
            _ => field_panic(self, "AssertsModifier"),
        })
    }

    // Go: ast/ast_generated.go:5551 ParameterName
    /// Go `node.AsX().ParameterName` for: TypePredicateNode.
    #[must_use]
    pub fn parameter_name(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TypePredicateNode(d) => Node::new(file, d.parameter_name),
            _ => field_panic(self, "ParameterName"),
        })
    }

    // Go: ast/ast_generated.go:5594 Value
    /// Go `node.AsX().Value` for: ImportAttribute.
    #[must_use]
    pub fn value(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ImportAttribute(d) => Node::new(file, d.value),
            _ => field_panic(self, "Value"),
        })
    }

    // Go: ast/ast_generated.go:5689 ExprName
    /// Go `node.AsX().ExprName` for: TypeQueryNode.
    #[must_use]
    pub fn expr_name(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TypeQueryNode(d) => Node::new(file, d.expr_name),
            _ => field_panic(self, "ExprName"),
        })
    }

    // Go: ast/ast_generated.go:5730 ReadonlyToken
    /// Go `node.AsX().ReadonlyToken` for: MappedTypeNode.
    #[must_use]
    pub fn readonly_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::MappedTypeNode(d) => opt_node(file, d.readonly_token),
            _ => field_panic(self, "ReadonlyToken"),
        })
    }

    // Go: ast/ast_generated.go:5732 NameType
    /// Go `node.AsX().NameType` for: MappedTypeNode.
    #[must_use]
    pub fn name_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::MappedTypeNode(d) => opt_node(file, d.name_type),
            _ => field_panic(self, "NameType"),
        })
    }

    // Go: ast/ast_generated.go:6267 IsSpread
    /// Go `node.AsX().IsSpread` for: SyntheticExpression.
    #[must_use]
    pub fn is_spread(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::SyntheticExpression(d) => d.is_spread,
            _ => field_panic(self, "IsSpread"),
        })
    }

    // Go: ast/ast_generated.go:6268 TupleNameSource
    /// Go `node.AsX().TupleNameSource` for: SyntheticExpression.
    #[must_use]
    pub fn tuple_name_source(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::SyntheticExpression(d) => opt_node(file, d.tuple_name_source),
            _ => field_panic(self, "TupleNameSource"),
        })
    }

    // Go: ast/ast_generated.go:6351 OpeningElement
    /// Go `node.AsX().OpeningElement` for: JsxElement.
    #[must_use]
    pub fn opening_element(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsxElement(d) => Node::new(file, d.opening_element),
            _ => field_panic(self, "OpeningElement"),
        })
    }

    // Go: ast/ast_generated.go:6353 ClosingElement
    /// Go `node.AsX().ClosingElement` for: JsxElement.
    #[must_use]
    pub fn closing_element(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsxElement(d) => Node::new(file, d.closing_element),
            _ => field_panic(self, "ClosingElement"),
        })
    }

    // Go: ast/ast_generated.go:6434 Namespace
    /// Go `node.AsX().Namespace` for: JsxNamespacedName.
    #[must_use]
    pub fn namespace(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsxNamespacedName(d) => Node::new(file, d.namespace),
            _ => field_panic(self, "Namespace"),
        })
    }

    // Go: ast/ast_generated.go:6565 OpeningFragment
    /// Go `node.AsX().OpeningFragment` for: JsxFragment.
    #[must_use]
    pub fn opening_fragment(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsxFragment(d) => Node::new(file, d.opening_fragment),
            _ => field_panic(self, "OpeningFragment"),
        })
    }

    // Go: ast/ast_generated.go:6567 ClosingFragment
    /// Go `node.AsX().ClosingFragment` for: JsxFragment.
    #[must_use]
    pub fn closing_fragment(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsxFragment(d) => Node::new(file, d.closing_fragment),
            _ => field_panic(self, "ClosingFragment"),
        })
    }

    // Go: ast/ast_generated.go:6814 ContainsOnlyTriviaWhiteSpaces
    /// Go `node.AsX().ContainsOnlyTriviaWhiteSpaces` for: JsxText.
    #[must_use]
    pub fn contains_only_trivia_white_spaces(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::JsxText(d) => d.contains_only_trivia_white_spaces,
            _ => field_panic(self, "ContainsOnlyTriviaWhiteSpaces"),
        })
    }

    // Go: ast/ast_generated.go:6879 Tags
    /// Go `node.AsX().Tags` for: JSDoc.
    #[must_use]
    pub fn tags(self) -> NodeList {
        list_of!(self, |d| match d {
            NodeData::JsDoc(d) => Some(d.tags.as_ref().map(AnyList::Nodes)),
            _ => None,
        })
        .unwrap_or_else(|| field_panic(self, "Tags"))
    }

    // Go: ast/ast_generated.go:7382 Constraint
    /// Go `node.AsX().Constraint` for: JSDocTemplateTag, TypeParameterDeclaration.
    #[must_use]
    pub fn constraint(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsDocTemplateTag(d) => Node::new(file, d.constraint),
            NodeData::TypeParameterDeclaration(d) => opt_node(file, d.constraint),
            _ => field_panic(self, "Constraint"),
        })
    }

    // Go: ast/ast_generated.go:7520 NameExpression
    /// Go `node.AsX().NameExpression` for: JSDocSeeTag.
    #[must_use]
    pub fn name_expression(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsDocSeeTag(d) => Node::new(file, d.name_expression),
            _ => field_panic(self, "NameExpression"),
        })
    }

    // Go: ast/ast_generated.go:8044 Keyword
    /// Go `node.AsX().Keyword` for: ModuleDeclaration.
    #[must_use]
    pub fn keyword(self) -> SyntaxKind {
        with_data!(self, |d| match d {
            NodeData::ModuleDeclaration(d) => d.keyword,
            _ => field_panic(self, "Keyword"),
        })
    }

    // Go: ast/ast_generated.go:8101 ModuleReference
    /// Go `node.AsX().ModuleReference` for: ImportEqualsDeclaration.
    #[must_use]
    pub fn module_reference(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ImportEqualsDeclaration(d) => Node::new(file, d.module_reference),
            _ => field_panic(self, "ModuleReference"),
        })
    }

    // Go: ast/ast_generated.go:8150 ExportClause
    /// Go `node.AsX().ExportClause` for: ExportDeclaration.
    #[must_use]
    pub fn export_clause(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ExportDeclaration(d) => opt_node(file, d.export_clause),
            _ => field_panic(self, "ExportClause"),
        })
    }

    // Go: ast/ast_generated.go:8197 IsTypeOf
    /// Go `node.AsX().IsTypeOf` for: ImportTypeNode.
    #[must_use]
    pub fn is_type_of(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::ImportTypeNode(d) => d.is_type_of,
            _ => field_panic(self, "IsTypeOf"),
        })
    }

    // Go: ast/ast_generated.go:8198 Argument
    /// Go `node.AsX().Argument` for: ImportTypeNode.
    #[must_use]
    pub fn argument(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ImportTypeNode(d) => Node::new(file, d.argument),
            _ => field_panic(self, "Argument"),
        })
    }

    // Go: ast/ast_generated.go:8200 Qualifier
    /// Go `node.AsX().Qualifier` for: ImportTypeNode.
    #[must_use]
    pub fn qualifier(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ImportTypeNode(d) => opt_node(file, d.qualifier),
            _ => field_panic(self, "Qualifier"),
        })
    }

    // Go: ast/ast_generated.go:8248 PhaseModifier
    /// Go `node.AsX().PhaseModifier` for: ImportClause.
    #[must_use]
    pub fn phase_modifier(self) -> SyntaxKind {
        with_data!(self, |d| match d {
            NodeData::ImportClause(d) => d.phase_modifier.unwrap_or(SyntaxKind::Unknown),
            _ => field_panic(self, "PhaseModifier"),
        })
    }

    // Go: ast/ast_generated.go:8250 NamedBindings
    /// Go `node.AsX().NamedBindings` for: ImportClause.
    #[must_use]
    pub fn named_bindings(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::ImportClause(d) => opt_node(file, d.named_bindings),
            _ => field_panic(self, "NamedBindings"),
        })
    }

    // Go: ast/ast_generated.go:8504 DefaultType
    /// Go `node.AsX().DefaultType` for: TypeParameterDeclaration.
    #[must_use]
    pub fn default_type(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::TypeParameterDeclaration(d) => opt_node(file, d.default_type),
            _ => field_panic(self, "DefaultType"),
        })
    }

    // Go: ast/ast_generated.go:8555 ThisArg
    /// Go `node.AsX().ThisArg` for: SyntheticReferenceExpression.
    #[must_use]
    pub fn this_arg(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::SyntheticReferenceExpression(d) => Node::new(file, d.this_arg),
            _ => field_panic(self, "ThisArg"),
        })
    }

    // Go: ast/ast_generated.go:8600 JSDocPropertyTags
    /// Go `node.AsX().JSDocPropertyTags` for: JSDocTypeLiteral.
    #[must_use]
    pub fn js_doc_property_tags(self) -> Vec<Node> {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::JsDocTypeLiteral(d) => d
                .js_doc_property_tags
                .as_ref()
                .map_or_else(Vec::new, |ids| {
                    ids.iter().map(|&id| Node::new(file, id)).collect()
                }),
            _ => field_panic(self, "JSDocPropertyTags"),
        })
    }

    // Go: ast/ast_generated.go:8601 IsArrayType
    /// Go `node.AsX().IsArrayType` for: JSDocTypeLiteral.
    #[must_use]
    pub fn is_array_type(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::JsDocTypeLiteral(d) => d.is_array_type,
            _ => field_panic(self, "IsArrayType"),
        })
    }

    // Go: ast/ast_generated.go:8642 IsBracketed
    /// Go `node.AsX().IsBracketed` for: JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn is_bracketed(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::JsDocParameterOrPropertyTag(d) => d.is_bracketed,
            _ => field_panic(self, "IsBracketed"),
        })
    }

    // Go: ast/ast_generated.go:8644 IsNameFirst
    /// Go `node.AsX().IsNameFirst` for: JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn is_name_first(self) -> bool {
        with_data!(self, |d| match d {
            NodeData::JsDocParameterOrPropertyTag(d) => d.is_name_first,
            _ => field_panic(self, "IsNameFirst"),
        })
    }

    // Go: ast/ast.go:2458 EndOfFileToken
    /// Go `node.AsX().EndOfFileToken` for: SourceFile.
    #[must_use]
    pub fn end_of_file_token(self) -> Node {
        let file = self.file_index();
        with_data!(self, |d| match d {
            NodeData::SourceFile(d) => Node::new(file, d.end_of_file_token),
            _ => field_panic(self, "EndOfFileToken"),
        })
    }
}

// ──────────────────────────────────────────────────────────────────────
// Kind guards (Go IsX(node) and IsXKind(kind))
// ──────────────────────────────────────────────────────────────────────

// Go: ast/ast_generated.go:609 IsToken
// PORT: Go lists every kind from KindUnknown to KindSourceKeyword (ts#63915)
// in one `case`. They are one range of the kind enum (astdata has the same
// order), so this checks the range.
#[inline]
#[must_use]
pub fn is_token(node: Node) -> bool {
    (SyntaxKind::Unknown as u16..=SyntaxKind::SourceKeyword as u16).contains(&(node.kind() as u16))
}

// Go: ast/ast_generated.go:638 IsIdentifier
#[inline]
#[must_use]
pub fn is_identifier(node: Node) -> bool {
    node.kind() == SyntaxKind::Identifier
}

// Go: ast/ast_generated.go:662 IsPrivateIdentifier
#[inline]
#[must_use]
pub fn is_private_identifier(node: Node) -> bool {
    node.kind() == SyntaxKind::PrivateIdentifier
}

// Go: ast/ast_generated.go:709 IsQualifiedName
#[inline]
#[must_use]
pub fn is_qualified_name(node: Node) -> bool {
    node.kind() == SyntaxKind::QualifiedName
}

// Go: ast/ast_generated.go:752 IsComputedPropertyName
#[inline]
#[must_use]
pub fn is_computed_property_name(node: Node) -> bool {
    node.kind() == SyntaxKind::ComputedPropertyName
}

// Go: ast/ast_generated.go:791 IsDecorator
#[inline]
#[must_use]
pub fn is_decorator(node: Node) -> bool {
    node.kind() == SyntaxKind::Decorator
}

// Go: ast/ast_generated.go:812 IsEmptyStatement
#[inline]
#[must_use]
pub fn is_empty_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::EmptyStatement
}

// Go: ast/ast_generated.go:861 IsIfStatement
#[inline]
#[must_use]
pub fn is_if_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::IfStatement
}

// Go: ast/ast_generated.go:906 IsDoStatement
#[inline]
#[must_use]
pub fn is_do_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::DoStatement
}

// Go: ast/ast_generated.go:951 IsWhileStatement
#[inline]
#[must_use]
pub fn is_while_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::WhileStatement
}

// Go: ast/ast_generated.go:1006 IsForStatement
#[inline]
#[must_use]
pub fn is_for_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForStatement
}

// Go: ast/ast_generated.go:1055 IsForInStatement
#[inline]
#[must_use]
pub fn is_for_in_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForInStatement
}

// Go: ast/ast_generated.go:1059 IsForOfStatement
#[inline]
#[must_use]
pub fn is_for_of_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForOfStatement
}

// Go: ast/ast_generated.go:1097 IsBreakStatement
#[inline]
#[must_use]
pub fn is_break_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::BreakStatement
}

// Go: ast/ast_generated.go:1135 IsContinueStatement
#[inline]
#[must_use]
pub fn is_continue_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ContinueStatement
}

// Go: ast/ast_generated.go:1174 IsReturnStatement
#[inline]
#[must_use]
pub fn is_return_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ReturnStatement
}

// Go: ast/ast_generated.go:1220 IsWithStatement
#[inline]
#[must_use]
pub fn is_with_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::WithStatement
}

// Go: ast/ast_generated.go:1266 IsSwitchStatement
#[inline]
#[must_use]
pub fn is_switch_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::SwitchStatement
}

// Go: ast/ast_generated.go:1310 IsCaseBlock
#[inline]
#[must_use]
pub fn is_case_block(node: Node) -> bool {
    node.kind() == SyntaxKind::CaseBlock
}

// Go: ast/ast_generated.go:1357 IsCaseClause
#[inline]
#[must_use]
pub fn is_case_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::CaseClause
}

// Go: ast/ast_generated.go:1361 IsDefaultClause
#[inline]
#[must_use]
pub fn is_default_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::DefaultClause
}

// Go: ast/ast_generated.go:1404 IsThrowStatement
#[inline]
#[must_use]
pub fn is_throw_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ThrowStatement
}

// Go: ast/ast_generated.go:1453 IsTryStatement
#[inline]
#[must_use]
pub fn is_try_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::TryStatement
}

// Go: ast/ast_generated.go:1495 IsCatchClause
#[inline]
#[must_use]
pub fn is_catch_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::CatchClause
}

// Go: ast/ast_generated.go:1516 IsDebuggerStatement
#[inline]
#[must_use]
pub fn is_debugger_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::DebuggerStatement
}

// Go: ast/ast_generated.go:1561 IsLabeledStatement
#[inline]
#[must_use]
pub fn is_labeled_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::LabeledStatement
}

// Go: ast/ast_generated.go:1603 IsExpressionStatement
#[inline]
#[must_use]
pub fn is_expression_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ExpressionStatement
}

// Go: ast/ast_generated.go:1649 IsBlock
#[inline]
#[must_use]
pub fn is_block(node: Node) -> bool {
    node.kind() == SyntaxKind::Block
}

// Go: ast/ast_generated.go:1690 IsVariableStatement
#[inline]
#[must_use]
pub fn is_variable_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableStatement
}

// Go: ast/ast_generated.go:1744 IsVariableDeclaration
#[inline]
#[must_use]
pub fn is_variable_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableDeclaration
}

// Go: ast/ast_generated.go:1785 IsVariableDeclarationList
#[inline]
#[must_use]
pub fn is_variable_declaration_list(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableDeclarationList
}

// Go: ast/ast_generated.go:1824 IsObjectBindingPattern
#[inline]
#[must_use]
pub fn is_object_binding_pattern(node: Node) -> bool {
    node.kind() == SyntaxKind::ObjectBindingPattern
}

// Go: ast/ast_generated.go:1828 IsArrayBindingPattern
#[inline]
#[must_use]
pub fn is_array_binding_pattern(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayBindingPattern
}

// Go: ast/ast_generated.go:1887 IsParameterDeclaration
#[inline]
#[must_use]
pub fn is_parameter_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::Parameter
}

// Go: ast/ast_generated.go:1942 IsBindingElement
#[inline]
#[must_use]
pub fn is_binding_element(node: Node) -> bool {
    node.kind() == SyntaxKind::BindingElement
}

// Go: ast/ast_generated.go:1981 IsMissingDeclaration
#[inline]
#[must_use]
pub fn is_missing_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MissingDeclaration
}

// Go: ast/ast_generated.go:2043 IsFunctionDeclaration
#[inline]
#[must_use]
pub fn is_function_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionDeclaration
}

// Go: ast/ast_generated.go:2094 IsClassDeclaration
#[inline]
#[must_use]
pub fn is_class_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassDeclaration
}

// Go: ast/ast_generated.go:2145 IsClassExpression
#[inline]
#[must_use]
pub fn is_class_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassExpression
}

// Go: ast/ast_generated.go:2186 IsHeritageClause
#[inline]
#[must_use]
pub fn is_heritage_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::HeritageClause
}

// Go: ast/ast_generated.go:2243 IsInterfaceDeclaration
#[inline]
#[must_use]
pub fn is_interface_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::InterfaceDeclaration
}

// Go: ast/ast_generated.go:2321 IsTypeAliasDeclaration
#[inline]
#[must_use]
pub fn is_type_alias_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeAliasDeclaration
}

// Go: ast/ast_generated.go:2325 IsJSTypeAliasDeclaration
#[inline]
#[must_use]
pub fn is_js_type_alias_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::JsTypeAliasDeclaration
}

// Go: ast/ast_generated.go:2371 IsEnumMember
#[inline]
#[must_use]
pub fn is_enum_member(node: Node) -> bool {
    node.kind() == SyntaxKind::EnumMember
}

// Go: ast/ast_generated.go:2420 IsEnumDeclaration
#[inline]
#[must_use]
pub fn is_enum_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::EnumDeclaration
}

// Go: ast/ast_generated.go:2463 IsModuleBlock
#[inline]
#[must_use]
pub fn is_module_block(node: Node) -> bool {
    node.kind() == SyntaxKind::ModuleBlock
}

// Go: ast/ast_generated.go:2484 IsNotEmittedStatement
#[inline]
#[must_use]
pub fn is_not_emitted_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::NotEmittedStatement
}

// Go: ast/ast_generated.go:2507 IsNotEmittedTypeElement
#[inline]
#[must_use]
pub fn is_not_emitted_type_element(node: Node) -> bool {
    node.kind() == SyntaxKind::NotEmittedTypeElement
}

// Go: ast/ast_generated.go:2586 IsImportDeclaration
#[inline]
#[must_use]
pub fn is_import_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportDeclaration
}

// Go: ast/ast_generated.go:2590 IsJSImportDeclaration
#[inline]
#[must_use]
pub fn is_js_import_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::JsImportDeclaration
}

// Go: ast/ast_generated.go:2632 IsExternalModuleReference
#[inline]
#[must_use]
pub fn is_external_module_reference(node: Node) -> bool {
    node.kind() == SyntaxKind::ExternalModuleReference
}

// Go: ast/ast_generated.go:2680 IsNamespaceImport
#[inline]
#[must_use]
pub fn is_namespace_import(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceImport
}

// Go: ast/ast_generated.go:2723 IsNamedImports
#[inline]
#[must_use]
pub fn is_named_imports(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedImports
}

// Go: ast/ast_generated.go:2769 IsExportAssignment
#[inline]
#[must_use]
pub fn is_export_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportAssignment
}

// Go: ast/ast_generated.go:2815 IsNamespaceExportDeclaration
#[inline]
#[must_use]
pub fn is_namespace_export_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceExportDeclaration
}

// Go: ast/ast_generated.go:2862 IsNamespaceExport
#[inline]
#[must_use]
pub fn is_namespace_export(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceExport
}

// Go: ast/ast_generated.go:2905 IsNamedExports
#[inline]
#[must_use]
pub fn is_named_exports(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedExports
}

// Go: ast/ast_generated.go:2954 IsExportSpecifier
#[inline]
#[must_use]
pub fn is_export_specifier(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportSpecifier
}

// Go: ast/ast_generated.go:2997 IsCallSignatureDeclaration
#[inline]
#[must_use]
pub fn is_call_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::CallSignature
}

// Go: ast/ast_generated.go:3040 IsConstructSignatureDeclaration
#[inline]
#[must_use]
pub fn is_construct_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ConstructSignature
}

// Go: ast/ast_generated.go:3093 IsConstructorDeclaration
#[inline]
#[must_use]
pub fn is_constructor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::Constructor
}

// Go: ast/ast_generated.go:3146 IsGetAccessorDeclaration
#[inline]
#[must_use]
pub fn is_get_accessor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::GetAccessor
}

// Go: ast/ast_generated.go:3199 IsSetAccessorDeclaration
#[inline]
#[must_use]
pub fn is_set_accessor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::SetAccessor
}

// Go: ast/ast_generated.go:3244 IsIndexSignatureDeclaration
#[inline]
#[must_use]
pub fn is_index_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::IndexSignature
}

// Go: ast/ast_generated.go:3300 IsMethodSignatureDeclaration
#[inline]
#[must_use]
pub fn is_method_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MethodSignature
}

// Go: ast/ast_generated.go:3364 IsMethodDeclaration
#[inline]
#[must_use]
pub fn is_method_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MethodDeclaration
}

// Go: ast/ast_generated.go:3419 IsPropertySignatureDeclaration
#[inline]
#[must_use]
pub fn is_property_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertySignature
}

// Go: ast/ast_generated.go:3474 IsPropertyDeclaration
#[inline]
#[must_use]
pub fn is_property_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyDeclaration
}

// Go: ast/ast_generated.go:3497 IsSemicolonClassElement
#[inline]
#[must_use]
pub fn is_semicolon_class_element(node: Node) -> bool {
    node.kind() == SyntaxKind::SemicolonClassElement
}

// Go: ast/ast_generated.go:3542 IsClassStaticBlockDeclaration
#[inline]
#[must_use]
pub fn is_class_static_block_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassStaticBlockDeclaration
}

// Go: ast/ast_generated.go:3563 IsOmittedExpression
#[inline]
#[must_use]
pub fn is_omitted_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::OmittedExpression
}

// Go: ast/ast_generated.go:3585 IsKeywordExpression
#[inline]
#[must_use]
pub fn is_keyword_expression(node: Node) -> bool {
    matches!(
        node.kind(),
        SyntaxKind::NullKeyword
            | SyntaxKind::TrueKeyword
            | SyntaxKind::FalseKeyword
            | SyntaxKind::ThisKeyword
            | SyntaxKind::SuperKeyword
            | SyntaxKind::ImportKeyword
    )
}

// Go: ast/ast_generated.go:3613 IsStringLiteral
#[inline]
#[must_use]
pub fn is_string_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::StringLiteral
}

// Go: ast/ast_generated.go:3637 IsNumericLiteral
#[inline]
#[must_use]
pub fn is_numeric_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::NumericLiteral
}

// Go: ast/ast_generated.go:3661 IsBigIntLiteral
#[inline]
#[must_use]
pub fn is_big_int_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::BigIntLiteral
}

// Go: ast/ast_generated.go:3685 IsRegularExpressionLiteral
#[inline]
#[must_use]
pub fn is_regular_expression_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::RegularExpressionLiteral
}

// Go: ast/ast_generated.go:3711 IsNoSubstitutionTemplateLiteral
#[inline]
#[must_use]
pub fn is_no_substitution_template_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::NoSubstitutionTemplateLiteral
}

// Go: ast/ast_generated.go:3763 IsBinaryExpression
#[inline]
#[must_use]
pub fn is_binary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::BinaryExpression
}

// Go: ast/ast_generated.go:3807 IsPrefixUnaryExpression
#[inline]
#[must_use]
pub fn is_prefix_unary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PrefixUnaryExpression
}

// Go: ast/ast_generated.go:3851 IsPostfixUnaryExpression
#[inline]
#[must_use]
pub fn is_postfix_unary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PostfixUnaryExpression
}

// Go: ast/ast_generated.go:3891 IsYieldExpression
#[inline]
#[must_use]
pub fn is_yield_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::YieldExpression
}

// Go: ast/ast_generated.go:3946 IsArrowFunction
#[inline]
#[must_use]
pub fn is_arrow_function(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrowFunction
}

// Go: ast/ast_generated.go:4008 IsFunctionExpression
#[inline]
#[must_use]
pub fn is_function_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionExpression
}

// Go: ast/ast_generated.go:4048 IsAsExpression
#[inline]
#[must_use]
pub fn is_as_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::AsExpression
}

// Go: ast/ast_generated.go:4088 IsSatisfiesExpression
#[inline]
#[must_use]
pub fn is_satisfies_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SatisfiesExpression
}

// Go: ast/ast_generated.go:4147 IsConditionalExpression
#[inline]
#[must_use]
pub fn is_conditional_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ConditionalExpression
}

// Go: ast/ast_generated.go:4197 IsPropertyAccessExpression
#[inline]
#[must_use]
pub fn is_property_access_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyAccessExpression
}

// Go: ast/ast_generated.go:4249 IsElementAccessExpression
#[inline]
#[must_use]
pub fn is_element_access_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ElementAccessExpression
}

// Go: ast/ast_generated.go:4300 IsCallExpression
#[inline]
#[must_use]
pub fn is_call_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::CallExpression
}

// Go: ast/ast_generated.go:4343 IsNewExpression
#[inline]
#[must_use]
pub fn is_new_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::NewExpression
}

// Go: ast/ast_generated.go:4389 IsMetaProperty
#[inline]
#[must_use]
pub fn is_meta_property(node: Node) -> bool {
    node.kind() == SyntaxKind::MetaProperty
}

// Go: ast/ast_generated.go:4429 IsNonNullExpression
#[inline]
#[must_use]
pub fn is_non_null_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::NonNullExpression
}

// Go: ast/ast_generated.go:4467 IsSpreadElement
#[inline]
#[must_use]
pub fn is_spread_element(node: Node) -> bool {
    node.kind() == SyntaxKind::SpreadElement
}

// Go: ast/ast_generated.go:4513 IsTemplateExpression
#[inline]
#[must_use]
pub fn is_template_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateExpression
}

// Go: ast/ast_generated.go:4558 IsTemplateSpan
#[inline]
#[must_use]
pub fn is_template_span(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateSpan
}

// Go: ast/ast_generated.go:4608 IsTaggedTemplateExpression
#[inline]
#[must_use]
pub fn is_tagged_template_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TaggedTemplateExpression
}

// Go: ast/ast_generated.go:4650 IsParenthesizedExpression
#[inline]
#[must_use]
pub fn is_parenthesized_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ParenthesizedExpression
}

// Go: ast/ast_generated.go:4695 IsArrayLiteralExpression
#[inline]
#[must_use]
pub fn is_array_literal_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayLiteralExpression
}

// Go: ast/ast_generated.go:4741 IsObjectLiteralExpression
#[inline]
#[must_use]
pub fn is_object_literal_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ObjectLiteralExpression
}

// Go: ast/ast_generated.go:4781 IsSpreadAssignment
#[inline]
#[must_use]
pub fn is_spread_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::SpreadAssignment
}

// Go: ast/ast_generated.go:4836 IsPropertyAssignment
#[inline]
#[must_use]
pub fn is_property_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyAssignment
}

// Go: ast/ast_generated.go:4894 IsShorthandPropertyAssignment
#[inline]
#[must_use]
pub fn is_shorthand_property_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::ShorthandPropertyAssignment
}

// Go: ast/ast_generated.go:4936 IsDeleteExpression
#[inline]
#[must_use]
pub fn is_delete_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::DeleteExpression
}

// Go: ast/ast_generated.go:4978 IsTypeOfExpression
#[inline]
#[must_use]
pub fn is_type_of_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeOfExpression
}

// Go: ast/ast_generated.go:5020 IsVoidExpression
#[inline]
#[must_use]
pub fn is_void_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::VoidExpression
}

// Go: ast/ast_generated.go:5058 IsAwaitExpression
#[inline]
#[must_use]
pub fn is_await_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::AwaitExpression
}

// Go: ast/ast_generated.go:5098 IsTypeAssertion
#[inline]
#[must_use]
pub fn is_type_assertion(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeAssertionExpression
}

// Go: ast/ast_generated.go:5119 IsKeywordTypeNode
#[inline]
#[must_use]
pub fn is_keyword_type_node(node: Node) -> bool {
    matches!(
        node.kind(),
        SyntaxKind::AnyKeyword
            | SyntaxKind::BigIntKeyword
            | SyntaxKind::BooleanKeyword
            | SyntaxKind::IntrinsicKeyword
            | SyntaxKind::NeverKeyword
            | SyntaxKind::NumberKeyword
            | SyntaxKind::ObjectKeyword
            | SyntaxKind::StringKeyword
            | SyntaxKind::SymbolKeyword
            | SyntaxKind::UndefinedKeyword
            | SyntaxKind::UnknownKeyword
            | SyntaxKind::VoidKeyword
    )
}

// Go: ast/ast_generated.go:5160 IsUnionTypeNode
#[inline]
#[must_use]
pub fn is_union_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::UnionType
}

// Go: ast/ast_generated.go:5197 IsIntersectionTypeNode
#[inline]
#[must_use]
pub fn is_intersection_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::IntersectionType
}

// Go: ast/ast_generated.go:5245 IsConditionalTypeNode
#[inline]
#[must_use]
pub fn is_conditional_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ConditionalType
}

// Go: ast/ast_generated.go:5285 IsTypeOperatorNode
#[inline]
#[must_use]
pub fn is_type_operator_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeOperator
}

// Go: ast/ast_generated.go:5323 IsInferTypeNode
#[inline]
#[must_use]
pub fn is_infer_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::InferType
}

// Go: ast/ast_generated.go:5361 IsArrayTypeNode
#[inline]
#[must_use]
pub fn is_array_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayType
}

// Go: ast/ast_generated.go:5401 IsIndexedAccessTypeNode
#[inline]
#[must_use]
pub fn is_indexed_access_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::IndexedAccessType
}

// Go: ast/ast_generated.go:5440 IsTypeReferenceNode
#[inline]
#[must_use]
pub fn is_type_reference_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeReference
}

// Go: ast/ast_generated.go:5481 IsExpressionWithTypeArguments
#[inline]
#[must_use]
pub fn is_expression_with_type_arguments(node: Node) -> bool {
    node.kind() == SyntaxKind::ExpressionWithTypeArguments
}

// Go: ast/ast_generated.go:5519 IsLiteralTypeNode
#[inline]
#[must_use]
pub fn is_literal_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::LiteralType
}

// Go: ast/ast_generated.go:5540 IsThisTypeNode
#[inline]
#[must_use]
pub fn is_this_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ThisType
}

// Go: ast/ast_generated.go:5582 IsTypePredicateNode
#[inline]
#[must_use]
pub fn is_type_predicate_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypePredicate
}

// Go: ast/ast_generated.go:5632 IsImportAttribute
#[inline]
#[must_use]
pub fn is_import_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportAttribute
}

// Go: ast/ast_generated.go:5679 IsImportAttributes
#[inline]
#[must_use]
pub fn is_import_attributes(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportAttributes
}

// Go: ast/ast_generated.go:5718 IsTypeQueryNode
#[inline]
#[must_use]
pub fn is_type_query_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeQuery
}

// Go: ast/ast_generated.go:5773 IsMappedTypeNode
#[inline]
#[must_use]
pub fn is_mapped_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::MappedType
}

// Go: ast/ast_generated.go:5812 IsTypeLiteralNode
#[inline]
#[must_use]
pub fn is_type_literal_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeLiteral
}

// Go: ast/ast_generated.go:5850 IsTupleTypeNode
#[inline]
#[must_use]
pub fn is_tuple_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TupleType
}

// Go: ast/ast_generated.go:5902 IsNamedTupleMember
#[inline]
#[must_use]
pub fn is_named_tuple_member(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedTupleMember
}

// Go: ast/ast_generated.go:5940 IsOptionalTypeNode
#[inline]
#[must_use]
pub fn is_optional_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::OptionalType
}

// Go: ast/ast_generated.go:5978 IsRestTypeNode
#[inline]
#[must_use]
pub fn is_rest_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::RestType
}

// Go: ast/ast_generated.go:6016 IsParenthesizedTypeNode
#[inline]
#[must_use]
pub fn is_parenthesized_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ParenthesizedType
}

// Go: ast/ast_generated.go:6055 IsFunctionTypeNode
#[inline]
#[must_use]
pub fn is_function_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionType
}

// Go: ast/ast_generated.go:6098 IsConstructorTypeNode
#[inline]
#[must_use]
pub fn is_constructor_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ConstructorType
}

// Go: ast/ast_generated.go:6124 IsTemplateHead
#[inline]
#[must_use]
pub fn is_template_head(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateHead
}

// Go: ast/ast_generated.go:6150 IsTemplateMiddle
#[inline]
#[must_use]
pub fn is_template_middle(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateMiddle
}

// Go: ast/ast_generated.go:6176 IsTemplateTail
#[inline]
#[must_use]
pub fn is_template_tail(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateTail
}

// Go: ast/ast_generated.go:6216 IsTemplateLiteralTypeNode
#[inline]
#[must_use]
pub fn is_template_literal_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateLiteralType
}

// Go: ast/ast_generated.go:6256 IsTemplateLiteralTypeSpan
#[inline]
#[must_use]
pub fn is_template_literal_type_span(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateLiteralTypeSpan
}

// Go: ast/ast_generated.go:6298 IsSyntheticExpression
#[inline]
#[must_use]
pub fn is_synthetic_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntheticExpression
}

// Go: ast/ast_generated.go:6340 IsPartiallyEmittedExpression
#[inline]
#[must_use]
pub fn is_partially_emitted_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PartiallyEmittedExpression
}

// Go: ast/ast_generated.go:6383 IsJsxElement
#[inline]
#[must_use]
pub fn is_jsx_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxElement
}

// Go: ast/ast_generated.go:6423 IsJsxAttributes
#[inline]
#[must_use]
pub fn is_jsx_attributes(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxAttributes
}

// Go: ast/ast_generated.go:6468 IsJsxNamespacedName
#[inline]
#[must_use]
pub fn is_jsx_namespaced_name(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxNamespacedName
}

// Go: ast/ast_generated.go:6511 IsJsxOpeningElement
#[inline]
#[must_use]
pub fn is_jsx_opening_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxOpeningElement
}

// Go: ast/ast_generated.go:6554 IsJsxSelfClosingElement
#[inline]
#[must_use]
pub fn is_jsx_self_closing_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxSelfClosingElement
}

// Go: ast/ast_generated.go:6597 IsJsxFragment
#[inline]
#[must_use]
pub fn is_jsx_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxFragment
}

// Go: ast/ast_generated.go:6618 IsJsxOpeningFragment
#[inline]
#[must_use]
pub fn is_jsx_opening_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxOpeningFragment
}

// Go: ast/ast_generated.go:6639 IsJsxClosingFragment
#[inline]
#[must_use]
pub fn is_jsx_closing_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxClosingFragment
}

// Go: ast/ast_generated.go:6685 IsJsxAttribute
#[inline]
#[must_use]
pub fn is_jsx_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxAttribute
}

// Go: ast/ast_generated.go:6725 IsJsxSpreadAttribute
#[inline]
#[must_use]
pub fn is_jsx_spread_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxSpreadAttribute
}

// Go: ast/ast_generated.go:6763 IsJsxClosingElement
#[inline]
#[must_use]
pub fn is_jsx_closing_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxClosingElement
}

// Go: ast/ast_generated.go:6803 IsJsxExpression
#[inline]
#[must_use]
pub fn is_jsx_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxExpression
}

// Go: ast/ast_generated.go:6829 IsJsxText
#[inline]
#[must_use]
pub fn is_jsx_text(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxText
}

// Go: ast/ast_generated.go:6868 IsSyntaxList
#[inline]
#[must_use]
pub fn is_syntax_list(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntaxList
}

// Go: ast/ast_generated.go:6908 IsJSDoc
#[inline]
#[must_use]
pub fn is_js_doc(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDoc
}

// Go: ast/ast_generated.go:6946 IsJSDocTypeExpression
#[inline]
#[must_use]
pub fn is_js_doc_type_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeExpression
}

// Go: ast/ast_generated.go:6984 IsJSDocNonNullableType
#[inline]
#[must_use]
pub fn is_js_doc_non_nullable_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNonNullableType
}

// Go: ast/ast_generated.go:7022 IsJSDocNullableType
#[inline]
#[must_use]
pub fn is_js_doc_nullable_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNullableType
}

// Go: ast/ast_generated.go:7043 IsJSDocAllType
#[inline]
#[must_use]
pub fn is_js_doc_all_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocAllType
}

// Go: ast/ast_generated.go:7081 IsJSDocVariadicType
#[inline]
#[must_use]
pub fn is_js_doc_variadic_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocVariadicType
}

// Go: ast/ast_generated.go:7119 IsJSDocOptionalType
#[inline]
#[must_use]
pub fn is_js_doc_optional_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOptionalType
}

// Go: ast/ast_generated.go:7159 IsJSDocTypeTag
#[inline]
#[must_use]
pub fn is_js_doc_type_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeTag
}

// Go: ast/ast_generated.go:7197 IsJSDocUnknownTag
#[inline]
#[must_use]
pub fn is_js_doc_unknown_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocUnknownTag
}

// Go: ast/ast_generated.go:7242 IsJSDocTemplateTag
#[inline]
#[must_use]
pub fn is_js_doc_template_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTemplateTag
}

// Go: ast/ast_generated.go:7282 IsJSDocReturnTag
#[inline]
#[must_use]
pub fn is_js_doc_return_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocReturnTag
}

// Go: ast/ast_generated.go:7320 IsJSDocPublicTag
#[inline]
#[must_use]
pub fn is_js_doc_public_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPublicTag
}

// Go: ast/ast_generated.go:7358 IsJSDocPrivateTag
#[inline]
#[must_use]
pub fn is_js_doc_private_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPrivateTag
}

// Go: ast/ast_generated.go:7396 IsJSDocProtectedTag
#[inline]
#[must_use]
pub fn is_js_doc_protected_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocProtectedTag
}

// Go: ast/ast_generated.go:7434 IsJSDocReadonlyTag
#[inline]
#[must_use]
pub fn is_js_doc_readonly_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocReadonlyTag
}

// Go: ast/ast_generated.go:7472 IsJSDocOverrideTag
#[inline]
#[must_use]
pub fn is_js_doc_override_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOverrideTag
}

// Go: ast/ast_generated.go:7510 IsJSDocDeprecatedTag
#[inline]
#[must_use]
pub fn is_js_doc_deprecated_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocDeprecatedTag
}

// Go: ast/ast_generated.go:7550 IsJSDocSeeTag
#[inline]
#[must_use]
pub fn is_js_doc_see_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSeeTag
}

// Go: ast/ast_generated.go:7590 IsJSDocImplementsTag
#[inline]
#[must_use]
pub fn is_js_doc_implements_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocImplementsTag
}

// Go: ast/ast_generated.go:7630 IsJSDocAugmentsTag
#[inline]
#[must_use]
pub fn is_js_doc_augments_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocAugmentsTag
}

// Go: ast/ast_generated.go:7670 IsJSDocSatisfiesTag
#[inline]
#[must_use]
pub fn is_js_doc_satisfies_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSatisfiesTag
}

// Go: ast/ast_generated.go:7710 IsJSDocThrowsTag
#[inline]
#[must_use]
pub fn is_js_doc_throws_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocThrowsTag
}

// Go: ast/ast_generated.go:7750 IsJSDocThisTag
#[inline]
#[must_use]
pub fn is_js_doc_this_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocThisTag
}

// Go: ast/ast_generated.go:7798 IsJSDocImportTag
#[inline]
#[must_use]
pub fn is_js_doc_import_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocImportTag
}

// Go: ast/ast_generated.go:7847 IsJSDocCallbackTag
#[inline]
#[must_use]
pub fn is_js_doc_callback_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocCallbackTag
}

// Go: ast/ast_generated.go:7887 IsJSDocOverloadTag
#[inline]
#[must_use]
pub fn is_js_doc_overload_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOverloadTag
}

// Go: ast/ast_generated.go:7936 IsJSDocTypedefTag
#[inline]
#[must_use]
pub fn is_js_doc_typedef_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypedefTag
}

// Go: ast/ast_generated.go:7977 IsJSDocSignature
#[inline]
#[must_use]
pub fn is_js_doc_signature(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSignature
}

// Go: ast/ast_generated.go:8019 IsJSDocNameReference
#[inline]
#[must_use]
pub fn is_js_doc_name_reference(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNameReference
}

// Go: ast/ast_generated.go:8027 IsSourceFile
#[inline]
#[must_use]
pub fn is_source_file(node: Node) -> bool {
    node.kind() == SyntaxKind::SourceFile
}

// Go: ast/ast_generated.go:8085 IsModuleDeclaration
#[inline]
#[must_use]
pub fn is_module_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ModuleDeclaration
}

// Go: ast/ast_generated.go:8136 IsImportEqualsDeclaration
#[inline]
#[must_use]
pub fn is_import_equals_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportEqualsDeclaration
}

// Go: ast/ast_generated.go:8187 IsExportDeclaration
#[inline]
#[must_use]
pub fn is_export_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportDeclaration
}

// Go: ast/ast_generated.go:8235 IsImportTypeNode
#[inline]
#[must_use]
pub fn is_import_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportType
}

// Go: ast/ast_generated.go:8284 IsImportClause
#[inline]
#[must_use]
pub fn is_import_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportClause
}

// Go: ast/ast_generated.go:8333 IsImportSpecifier
#[inline]
#[must_use]
pub fn is_import_specifier(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportSpecifier
}

// Go: ast/ast_generated.go:8356 IsJSDocText
#[inline]
#[must_use]
pub fn is_js_doc_text(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocText
}

// Go: ast/ast_generated.go:8400 IsJSDocLink
#[inline]
#[must_use]
pub fn is_js_doc_link(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLink
}

// Go: ast/ast_generated.go:8444 IsJSDocLinkPlain
#[inline]
#[must_use]
pub fn is_js_doc_link_plain(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLinkPlain
}

// Go: ast/ast_generated.go:8488 IsJSDocLinkCode
#[inline]
#[must_use]
pub fn is_js_doc_link_code(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLinkCode
}

// Go: ast/ast_generated.go:8544 IsTypeParameterDeclaration
#[inline]
#[must_use]
pub fn is_type_parameter_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeParameter
}

// Go: ast/ast_generated.go:8589 IsSyntheticReferenceExpression
#[inline]
#[must_use]
pub fn is_synthetic_reference_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntheticReferenceExpression
}

// Go: ast/ast_generated.go:8631 IsJSDocTypeLiteral
#[inline]
#[must_use]
pub fn is_js_doc_type_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeLiteral
}

// Go: ast/ast_generated.go:8681 IsJSDocParameterTag
#[inline]
#[must_use]
pub fn is_js_doc_parameter_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocParameterTag
}

// Go: ast/ast_generated.go:8685 IsJSDocPropertyTag
#[inline]
#[must_use]
pub fn is_js_doc_property_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPropertyTag
}

// Go: ast/ast_generated.go:9810 IsTriviaKind
#[inline]
#[must_use]
pub fn is_trivia_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::SingleLineCommentTrivia
        | SyntaxKind::MultiLineCommentTrivia
        | SyntaxKind::NewLineTrivia
        | SyntaxKind::WhitespaceTrivia
        | SyntaxKind::ConflictMarkerTrivia => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9818 IsLiteralKind
#[inline]
#[must_use]
pub fn is_literal_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_LITERAL_TOKEN as u16)
        && (kind as u16) <= (SyntaxKind::LAST_LITERAL_TOKEN as u16)
}

// Go: ast/ast_generated.go:9822 IsPseudoLiteralKind
#[inline]
#[must_use]
pub fn is_pseudo_literal_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::TemplateHead | SyntaxKind::TemplateMiddle | SyntaxKind::TemplateTail => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9830 IsPunctuationKind
#[inline]
#[must_use]
pub fn is_punctuation_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_PUNCTUATION as u16)
        && (kind as u16) <= (SyntaxKind::LAST_PUNCTUATION as u16)
}

// Go: ast/ast_generated.go:9834 IsKeywordKind
#[inline]
#[must_use]
pub fn is_keyword_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_KEYWORD as u16)
        && (kind as u16) <= (SyntaxKind::LAST_KEYWORD as u16)
}

// Go: ast/ast_generated.go:9838 IsModifierKind
#[inline]
#[must_use]
pub fn is_modifier_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AbstractKeyword
        | SyntaxKind::AccessorKeyword
        | SyntaxKind::AsyncKeyword
        | SyntaxKind::ConstKeyword
        | SyntaxKind::DeclareKeyword
        | SyntaxKind::DefaultKeyword
        | SyntaxKind::ExportKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::PrivateKeyword
        | SyntaxKind::ProtectedKeyword
        | SyntaxKind::PublicKeyword
        | SyntaxKind::ReadonlyKeyword
        | SyntaxKind::OutKeyword
        | SyntaxKind::OverrideKeyword
        | SyntaxKind::StaticKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9846 IsKeywordTypeKind
#[inline]
#[must_use]
pub fn is_keyword_type_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AnyKeyword
        | SyntaxKind::BigIntKeyword
        | SyntaxKind::BooleanKeyword
        | SyntaxKind::IntrinsicKeyword
        | SyntaxKind::NeverKeyword
        | SyntaxKind::NumberKeyword
        | SyntaxKind::ObjectKeyword
        | SyntaxKind::StringKeyword
        | SyntaxKind::SymbolKeyword
        | SyntaxKind::UndefinedKeyword
        | SyntaxKind::UnknownKeyword
        | SyntaxKind::VoidKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9854 IsKeywordExpressionKind
#[inline]
#[must_use]
pub fn is_keyword_expression_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::NullKeyword
        | SyntaxKind::TrueKeyword
        | SyntaxKind::FalseKeyword
        | SyntaxKind::ThisKeyword
        | SyntaxKind::SuperKeyword
        | SyntaxKind::ImportKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9862 IsTokenKind
#[inline]
#[must_use]
pub fn is_token_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_TOKEN as u16)
        && (kind as u16) <= (SyntaxKind::LAST_TOKEN as u16)
}

// Go: ast/ast_generated.go:9866 IsJsxTokenKind
#[inline]
#[must_use]
pub fn is_jsx_token_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanSlashToken
        | SyntaxKind::EndOfFile
        | SyntaxKind::ConflictMarkerTrivia
        | SyntaxKind::JsxText
        | SyntaxKind::JsxTextAllWhiteSpaces
        | SyntaxKind::OpenBraceToken
        | SyntaxKind::LessThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9874 IsJSDocNodeKind
#[inline]
#[must_use]
pub fn is_js_doc_node_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_JS_DOC_NODE as u16)
        && (kind as u16) <= (SyntaxKind::LAST_JS_DOC_NODE as u16)
}

// Go: ast/ast_generated.go:9878 IsImportPhaseModifierKind
#[inline]
#[must_use]
pub fn is_import_phase_modifier_kind(kind: SyntaxKind) -> bool {
    match kind {
        // ts#63915: SourceKeyword
        SyntaxKind::TypeKeyword | SyntaxKind::DeferKeyword | SyntaxKind::SourceKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9886 IsPostfixUnaryOperator
#[inline]
#[must_use]
pub fn is_postfix_unary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusPlusToken | SyntaxKind::MinusMinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9894 IsPrefixUnaryOperator
#[inline]
#[must_use]
pub fn is_prefix_unary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::TildeToken
        | SyntaxKind::ExclamationToken
        | SyntaxKind::PlusPlusToken
        | SyntaxKind::MinusMinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9902 IsAssignmentOperator
#[inline]
#[must_use]
pub fn is_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9910 IsBinaryOperator
#[inline]
#[must_use]
pub fn is_binary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::QuestionQuestionToken
        | SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken
        | SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken
        | SyntaxKind::CommaToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9918 IsExponentiationOperator
#[inline]
#[must_use]
pub fn is_exponentiation_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9926 IsMultiplicativeOperator
#[inline]
#[must_use]
pub fn is_multiplicative_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskToken | SyntaxKind::SlashToken | SyntaxKind::PercentToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9934 IsMultiplicativeOperatorOrHigher
#[inline]
#[must_use]
pub fn is_multiplicative_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9942 IsAdditiveOperator
#[inline]
#[must_use]
pub fn is_additive_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusToken | SyntaxKind::MinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9950 IsAdditiveOperatorOrHigher
#[inline]
#[must_use]
pub fn is_additive_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9958 IsShiftOperator
#[inline]
#[must_use]
pub fn is_shift_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9966 IsShiftOperatorOrHigher
#[inline]
#[must_use]
pub fn is_shift_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9974 IsRelationalOperator
#[inline]
#[must_use]
pub fn is_relational_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9982 IsRelationalOperatorOrHigher
#[inline]
#[must_use]
pub fn is_relational_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9990 IsEqualityOperator
#[inline]
#[must_use]
pub fn is_equality_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9998 IsEqualityOperatorOrHigher
#[inline]
#[must_use]
pub fn is_equality_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10006 IsBitwiseOperator
#[inline]
#[must_use]
pub fn is_bitwise_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandToken | SyntaxKind::BarToken | SyntaxKind::CaretToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10014 IsBitwiseOperatorOrHigher
#[inline]
#[must_use]
pub fn is_bitwise_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10022 IsLogicalOperator
#[inline]
#[must_use]
pub fn is_logical_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandAmpersandToken | SyntaxKind::BarBarToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10030 IsLogicalOperatorOrHigher
#[inline]
#[must_use]
pub fn is_logical_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10038 IsCompoundAssignmentOperator
#[inline]
#[must_use]
pub fn is_compound_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10046 IsAssignmentOperatorOrHigher
#[inline]
#[must_use]
pub fn is_assignment_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::QuestionQuestionToken
        | SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken
        | SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:10054 IsLogicalOrCoalescingAssignmentOperator
#[inline]
#[must_use]
pub fn is_logical_or_coalescing_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}
